name: khulnaservice
description: Khulna Service
version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^1.0.0
  getflutter: ^1.0.11
  validators: ^2.0.0+1
  flutter_icons: ^1.1.0
  flutter_svg: ^0.18.0
  provider: ^4.2.0
  flutter_material_color_picker: ^1.0.5
  shared_preferences: ^0.5.7
  convex_bottom_bar: ^2.4.1
  webview_flutter: ^0.3.22+1
  badges: ^1.1.1
  page_transition: ^1.1.5
  carousel_slider: ^2.1.0
  clippy_flutter: ^1.1.1
  auto_size_text: ^2.1.0
  flutter_rating_bar: ^3.0.1+1
  like_button: ^0.2.0
  flutter_phoenix: ^0.1.0
  flutter_countdown_timer: ^1.1.0
  bubble_tab_indicator: ^0.1.4
  rxdart: ">=0.23.0 <0.24.0"
  expandable: ^4.1.3
  flutter_translate: ^1.6.0
  searchable_dropdown: ^1.1.3
  path_provider: ^1.6.11
  hive_flutter: ^0.3.1
  file_picker: ^1.13.3
  html: ^0.14.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/i18n/

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
